# Generated by Django 5.1.4 on 2025-01-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieta',
            name='prompt',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
