# Generated by Django 5.1.4 on 2025-01-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini_api', '0003_remove_dieta_calorias_remove_dieta_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieta',
            name='diet',
            field=models.TextField(default=1, verbose_name='Criar Dieta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dieta',
            name='train',
            field=models.TextField(default=1, verbose_name='Modelo de Treino'),
            preserve_default=False,
        ),
    ]
